#pragma once

const unsigned short G_ORANGE = 0xE2C2; //0xFDA0;
const unsigned short G_BROWN = 0xFF30;
const unsigned short SKY_COLOR = 0x000E;
const unsigned short HILL_COLOR = 0x0560;
const unsigned short BLACK = 0x0000;
const unsigned short P_BROWN = 0xC300;
const unsigned short K_ORANGE = 0xE2C2;
const unsigned short K_BROWN = 0xFF30;
const unsigned short K_GREEN = 0x0560;
const unsigned short K_YELLOW = 0xFFE0;
const unsigned short WHITE = 0xFFFF;
const unsigned short C_BROWN = 0x9A40;
const unsigned short C_GOLD = 0xE4E4;
const unsigned short C_BLUE = 0x3DFF;

const unsigned short BLOCK[361]  = 
{
  SKY_COLOR, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40, 0x9A40,   // 0x0010 (16) pixels
  0x9A40, 0x9A40, SKY_COLOR, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0020 (32) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, BLACK, BLACK, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0030 (48) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, BLACK, 0xE4E4, BLACK, 0x9A40, 0xE4E4, BLACK, BLACK, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0040 (64) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, BLACK, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0050 (80) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40,   // 0x0060 (96) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0070 (112) pixels
  0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0080 (128) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0090 (144) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x00A0 (160) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x00B0 (176) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4,   // 0x00C0 (192) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x00D0 (208) pixels
  BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x00E0 (224) pixels
  0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x00F0 (240) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0100 (256) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0110 (272) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, 0x9A40, 0xE4E4, BLACK,   // 0x0120 (288) pixels
  BLACK, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, BLACK, 0xE4E4, BLACK,   // 0x0130 (304) pixels
  0x9A40, 0xE4E4, BLACK, BLACK, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK,   // 0x0140 (320) pixels
  BLACK, 0xE4E4, BLACK, 0x9A40, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4,   // 0x0150 (336) pixels
  0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, 0xE4E4, BLACK, SKY_COLOR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,   // 0x0160 (352) pixels
};

const byte BLOCK_SIZE[2]  = {19, 19};

const unsigned short PIPE[195] =
  {
    0x0560, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 
    0xBFE3, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0xBFE3, 
    0xBFE3, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0xBFE3, 0xBFE3,
    0xBFE3, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0xBFE3, 0xBFE3, 
    0xBFE3, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0xBFE3, 0xBFE3, 
    0xBFE3, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0xBFE3, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR,
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0x0560, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR, 
    SKY_COLOR, SKY_COLOR, 0x0560, 0xBFE3, 0xBFE3, 0x0560, 0xBFE3, 0x0560, 0x0560, 0x0560, 0x0560, SKY_COLOR, SKY_COLOR,
  };
const unsigned short CLOUD1[156] =
{
  SKY_COLOR, BLACK, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
  BLACK, WHITE, WHITE, WHITE, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
  BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
  WHITE, C_BLUE, WHITE, WHITE, C_BLUE, WHITE, WHITE, BLACK, WHITE, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
  C_BLUE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, SKY_COLOR, 
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, 
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, 
  WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, SKY_COLOR, 
  WHITE, WHITE, WHITE, C_BLUE, C_BLUE, WHITE, C_BLUE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, 
  C_BLUE, C_BLUE, C_BLUE, WHITE, WHITE, C_BLUE, WHITE, WHITE, WHITE, WHITE, BLACK, SKY_COLOR, SKY_COLOR, 
  WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
  BLACK, BLACK, SKY_COLOR, BLACK, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR 
};

const unsigned short CLOUD2[156] =
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
  SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK, SKY_COLOR, 
  SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, 
  SKY_COLOR, SKY_COLOR, BLACK, BLACK, WHITE, WHITE, WHITE, C_BLUE, WHITE, WHITE, C_BLUE, WHITE, WHITE, 
  SKY_COLOR, BLACK, WHITE, WHITE, WHITE, WHITE, C_BLUE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, 
  BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, 
  BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, 
  BLACK, WHITE, WHITE, WHITE, C_BLUE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, 
  SKY_COLOR, BLACK, BLACK, WHITE, WHITE, C_BLUE, WHITE, WHITE, WHITE, C_BLUE, C_BLUE, WHITE, C_BLUE, 
  SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, WHITE, WHITE, C_BLUE, C_BLUE, C_BLUE, WHITE, WHITE, C_BLUE, WHITE, 
  SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, BLACK, 
  SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, SKY_COLOR, BLACK, BLACK, BLACK, SKY_COLOR 
};

const unsigned short GROUND[64] =
{
  0xE2C2, 0xF6B6, 0xF6B6, 0xF6B6, BLACK, 0xE2C2, 0xF6B6, 0xE2C2, 0xF6B6, 0xE2C2, 0xE2C2, 0xE2C2, BLACK, 0xF6B6, 0xE2C2, BLACK,   // 0x0010 (16) pixels
  0xF6B6, 0xE2C2, 0xE2C2, 0xE2C2, BLACK, 0xE2C2, BLACK, 0xE2C2, BLACK, 0xE2C2, 0xE2C2, 0xE2C2, BLACK, 0xF6B6, 0xF6B6, BLACK,   // 0x0020 (32) pixels
  0xF6B6, BLACK, BLACK, 0xE2C2, BLACK, 0xF6B6, 0xE2C2, BLACK, 0xF6B6, 0xF6B6, 0xF6B6, BLACK, 0xF6B6, 0xE2C2, 0xE2C2, BLACK,   // 0x0030 (48) pixels
  0xF6B6, 0xE2C2, 0xE2C2, 0xF6B6, 0xE2C2, 0xE2C2, 0xE2C2, BLACK, 0xE2C2, BLACK, BLACK, 0xF6B6, BLACK, BLACK, BLACK, 0xE2C2,   // 0x0040 (64) pixels
};


const unsigned short SKY[440] =
{
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0010 (16) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0020 (32) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0030 (48) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0040 (64) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0050 (80) pixels
BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0060 (96) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0070 (112) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0080 (128) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, BLACK, 0x0560,   // 0x0090 (144) pixels
0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x00A0 (160) pixels
0x0560, 0x0560, BLACK, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x00B0 (176) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, 0x0560, BLACK, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x00C0 (192) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x00D0 (208) pixels
BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x00E0 (224) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x00F0 (240) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0100 (256) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK,   // 0x0110 (272) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x0120 (288) pixels
0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x0130 (304) pixels
0x0560, 0x0560, BLACK, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,   // 0x0140 (320) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR,   // 0x0150 (336) pixels
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, 0x0560, BLACK, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x0160 (352) pixels
0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, 0x0560, 0x0560, 0x0560,   // 0x0170 (368) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x0180 (384) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, BLACK, SKY_COLOR, SKY_COLOR,   // 0x0190 (400) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x01A0 (416) pixels
0x0560, 0x0560, BLACK, SKY_COLOR, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560,   // 0x01B0 (432) pixels
0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560, 0x0560 };

const unsigned short PIRANHA_SPRITE[81] = 
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, K_GREEN, WHITE, K_GREEN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, K_GREEN, K_YELLOW, WHITE, K_GREEN, K_YELLOW, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, K_GREEN, K_YELLOW, K_GREEN, WHITE, K_YELLOW, K_GREEN, K_GREEN, SKY_COLOR,
  SKY_COLOR, K_GREEN, K_GREEN, K_YELLOW, WHITE, K_GREEN, K_YELLOW, K_GREEN, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, K_YELLOW, K_GREEN, K_YELLOW, K_GREEN, K_YELLOW, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, K_GREEN, K_YELLOW, K_GREEN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  P_BROWN, P_BROWN, SKY_COLOR, SKY_COLOR, K_GREEN, SKY_COLOR, SKY_COLOR, P_BROWN, P_BROWN,
  SKY_COLOR, P_BROWN, P_BROWN, SKY_COLOR, P_BROWN, SKY_COLOR, P_BROWN, P_BROWN, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, P_BROWN, P_BROWN, P_BROWN, P_BROWN, P_BROWN, SKY_COLOR, SKY_COLOR, 
 };

const unsigned short PIRANHA_SPRITE_TOP[27] = 
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, K_YELLOW, WHITE, K_GREEN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, K_GREEN, K_GREEN, WHITE, K_GREEN, K_YELLOW, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, K_GREEN, K_YELLOW, K_GREEN, WHITE, K_YELLOW, K_GREEN, K_GREEN, SKY_COLOR,
};

const unsigned short PIRANHA_SPRITE_MIDDLE[54] =
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, K_GREEN, WHITE, K_GREEN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, K_GREEN, K_YELLOW, WHITE, K_GREEN, K_GREEN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, K_GREEN, K_GREEN, K_GREEN, WHITE, K_GREEN, K_GREEN, K_YELLOW, SKY_COLOR,
  SKY_COLOR, K_GREEN, K_YELLOW, K_GREEN, K_GREEN, K_GREEN, K_GREEN, K_GREEN, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, K_GREEN, K_GREEN, K_GREEN, K_YELLOW, K_GREEN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, K_GREEN, K_GREEN, K_GREEN, SKY_COLOR, SKY_COLOR, SKY_COLOR
};
const unsigned short PIRANHA_SPRITE_OPEN[81] = 
{
  SKY_COLOR, WHITE, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, WHITE, SKY_COLOR,
  K_GREEN, K_YELLOW, WHITE, SKY_COLOR, SKY_COLOR, SKY_COLOR, WHITE, K_GREEN, K_YELLOW,
  K_GREEN, K_GREEN, K_GREEN, WHITE, SKY_COLOR, WHITE, K_GREEN, K_YELLOW, K_GREEN,
  K_GREEN, K_GREEN, K_YELLOW, WHITE, SKY_COLOR, WHITE, K_GREEN, K_GREEN, K_GREEN,
  SKY_COLOR, K_YELLOW, K_GREEN, K_GREEN, SKY_COLOR, K_GREEN, K_YELLOW, K_GREEN, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, K_GREEN, K_YELLOW, K_GREEN, K_GREEN, K_YELLOW, SKY_COLOR, SKY_COLOR,
  P_BROWN, P_BROWN, SKY_COLOR, K_GREEN, K_GREEN, K_GREEN, SKY_COLOR, P_BROWN, P_BROWN,
  SKY_COLOR, P_BROWN, P_BROWN, SKY_COLOR, P_BROWN, SKY_COLOR, P_BROWN, P_BROWN, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, P_BROWN, P_BROWN, P_BROWN, P_BROWN, P_BROWN, SKY_COLOR, SKY_COLOR, 
};


const unsigned short GOOMBA_RIGHT[169] = {
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE ,G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, G_ORANGE, BLACK, BLACK, G_ORANGE ,G_ORANGE, G_ORANGE, BLACK, BLACK, G_ORANGE, SKY_COLOR, SKY_COLOR,
SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, BLACK, BLACK, G_ORANGE, BLACK, BLACK, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR,
G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_BROWN, BLACK, BLACK, BLACK, G_BROWN, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,
G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_BROWN, BLACK ,G_ORANGE, BLACK, G_BROWN, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,
G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE ,G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,
SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_BROWN, G_BROWN ,G_BROWN, G_BROWN, G_BROWN, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, G_BROWN, G_BROWN ,G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, BLACK, BLACK, G_BROWN, G_BROWN, G_BROWN, G_BROWN, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
SKY_COLOR, BLACK, BLACK, BLACK, BLACK, G_BROWN, G_BROWN, G_BROWN, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, BLACK, BLACK, BLACK, BLACK, SKY_COLOR, SKY_COLOR, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
 };

const unsigned short GOOMBA_LEFT[169] = {
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE ,G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, G_ORANGE, BLACK, BLACK, G_ORANGE ,G_ORANGE, G_ORANGE, BLACK, BLACK, G_ORANGE, SKY_COLOR, SKY_COLOR,
SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, BLACK, BLACK, G_ORANGE, BLACK, BLACK, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR,
G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_BROWN, BLACK, BLACK, BLACK, G_BROWN, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,
G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_BROWN, BLACK ,G_ORANGE, BLACK, G_BROWN, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,
G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE ,G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,
SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_BROWN, G_BROWN ,G_BROWN, G_BROWN, G_BROWN, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, G_BROWN, G_BROWN ,G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, G_BROWN, G_BROWN, G_BROWN, G_BROWN, BLACK, BLACK, SKY_COLOR, SKY_COLOR, 
SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, G_BROWN, G_BROWN, G_BROWN, BLACK, BLACK, BLACK, BLACK, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, SKY_COLOR, SKY_COLOR, BLACK, BLACK, BLACK, BLACK, SKY_COLOR,
 };

const unsigned short GOOMBA_SMASH[169] = {
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, SKY_COLOR, 
SKY_COLOR, SKY_COLOR, SKY_COLOR, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE, G_ORANGE,G_ORANGE, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, G_ORANGE, BLACK, BLACK, G_ORANGE, G_ORANGE,G_ORANGE, BLACK, BLACK, G_ORANGE, SKY_COLOR, SKY_COLOR, 
SKY_COLOR, G_ORANGE, G_ORANGE, WHITE, WHITE, BLACK, BLACK, BLACK, WHITE, WHITE, G_ORANGE, G_ORANGE, SKY_COLOR, 
SKY_COLOR, SKY_COLOR, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, SKY_COLOR, SKY_COLOR,
SKY_COLOR, SKY_COLOR, SKY_COLOR, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, G_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
SKY_COLOR, BLACK, BLACK, BLACK, BLACK, SKY_COLOR, SKY_COLOR, SKY_COLOR, BLACK, BLACK, BLACK, BLACK, SKY_COLOR
 };
const unsigned short KOOPA_RIGHT_CLOSED[130] = 
{
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,WHITE,SKY_COLOR,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,WHITE,WHITE,WHITE,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,WHITE,K_GREEN,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,WHITE,WHITE,SKY_COLOR,
SKY_COLOR,SKY_COLOR,K_GREEN,K_GREEN,K_GREEN,K_BROWN,K_BROWN,K_BROWN,K_BROWN,K_BROWN,
SKY_COLOR,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,
K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_BROWN,SKY_COLOR,SKY_COLOR,K_BROWN,
K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_BROWN,SKY_COLOR,SKY_COLOR,
K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,WHITE,SKY_COLOR,
WHITE,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,WHITE,SKY_COLOR,
SKY_COLOR,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,SKY_COLOR,SKY_COLOR,
SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,
SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR
};
const unsigned short KOOPA_RIGHT_OPEN[130] = 
{
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,WHITE,SKY_COLOR,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,WHITE,WHITE,WHITE,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,WHITE,K_GREEN,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,WHITE,WHITE,SKY_COLOR,
SKY_COLOR,SKY_COLOR,K_GREEN,K_GREEN,K_GREEN,K_BROWN,K_BROWN,K_BROWN,K_BROWN,K_BROWN,
SKY_COLOR,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,
K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_BROWN,SKY_COLOR,SKY_COLOR,K_BROWN,
K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_BROWN,SKY_COLOR,SKY_COLOR,
K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,WHITE,SKY_COLOR,
WHITE,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,WHITE,SKY_COLOR,
SKY_COLOR,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,SKY_COLOR,SKY_COLOR,
SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,K_BROWN,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR
};

const unsigned short KOOPA_LEFT_OPEN[130] = 
{
SKY_COLOR,SKY_COLOR,WHITE,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,WHITE,WHITE,WHITE,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,K_GREEN,WHITE,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,WHITE,WHITE,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
K_BROWN,K_BROWN,K_BROWN,K_BROWN,K_BROWN,K_GREEN,K_GREEN,K_GREEN,SKY_COLOR,SKY_COLOR,
K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,SKY_COLOR,
K_BROWN,SKY_COLOR,SKY_COLOR,K_BROWN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,
SKY_COLOR,SKY_COLOR,K_BROWN,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,
SKY_COLOR,WHITE,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,
SKY_COLOR,WHITE,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,WHITE,K_GREEN,
SKY_COLOR,SKY_COLOR,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR, K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,
SKY_COLOR,SKY_COLOR, K_BROWN,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,K_BROWN,SKY_COLOR
};
const unsigned short KOOPA_LEFT_CLOSED[130] = 
{
SKY_COLOR,SKY_COLOR,WHITE,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,WHITE,WHITE,WHITE,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,K_GREEN,WHITE,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
SKY_COLOR,WHITE,WHITE,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
K_BROWN,K_BROWN,K_BROWN,K_BROWN,K_BROWN,K_GREEN,K_GREEN,K_GREEN,SKY_COLOR,SKY_COLOR,
K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,SKY_COLOR,
K_BROWN,SKY_COLOR,SKY_COLOR,K_BROWN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,
SKY_COLOR,SKY_COLOR,K_BROWN,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,
SKY_COLOR,WHITE,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,
SKY_COLOR,WHITE,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,WHITE,K_GREEN,
SKY_COLOR,SKY_COLOR,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,SKY_COLOR,
SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,
SKY_COLOR,SKY_COLOR,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,K_BROWN,K_BROWN,SKY_COLOR,SKY_COLOR
};


const unsigned short KOOPA_HIDE[130] = 
{
  SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,SKY_COLOR,K_GREEN,K_GREEN,K_GREEN,K_GREEN,SKY_COLOR,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,SKY_COLOR,SKY_COLOR,
  SKY_COLOR,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,SKY_COLOR,
  K_GREEN,K_GREEN,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_GREEN,
  WHITE,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,WHITE,
  WHITE,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_YELLOW,K_GREEN,WHITE,
  SKY_COLOR, WHITE,K_YELLOW,K_GREEN,K_GREEN,K_GREEN,K_GREEN,K_GREEN,WHITE,SKY_COLOR,
  SKY_COLOR,SKY_COLOR,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,SKY_COLOR,SKY_COLOR
};

const unsigned short COIN_1[11*8] = 
{
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_GOLD, C_GOLD, C_GOLD, SKY_COLOR,
  SKY_COLOR, C_GOLD, C_GOLD, C_BROWN, C_BROWN, C_GOLD, C_GOLD, SKY_COLOR,
  C_GOLD, C_GOLD, C_BROWN, C_GOLD, C_GOLD, BLACK, C_GOLD, C_GOLD,
  C_GOLD, C_GOLD, C_BROWN, C_GOLD, C_GOLD, BLACK, C_GOLD, C_GOLD,
  C_GOLD, C_GOLD, C_BROWN, C_GOLD, C_GOLD, BLACK, C_GOLD, C_GOLD,
  C_GOLD, C_GOLD, C_BROWN, C_GOLD, C_GOLD, BLACK, C_GOLD, C_GOLD,
  C_GOLD, C_GOLD, C_BROWN, C_GOLD, C_GOLD, BLACK, C_GOLD, C_GOLD,
  SKY_COLOR, C_GOLD, C_GOLD, BLACK, BLACK, C_GOLD, C_GOLD, SKY_COLOR,
  SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_GOLD, C_GOLD, C_GOLD, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR
};

const unsigned short COIN_4[11*8] = 
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, G_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR
};

const unsigned short COIN_3[11*8] = 
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, G_BROWN, G_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_GOLD, SKY_COLOR, SKY_COLOR, SKY_COLOR
};

const unsigned short COIN_2[11*8] = 
{
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, G_BROWN, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, C_BROWN, C_BROWN, SKY_COLOR, SKY_COLOR,
  SKY_COLOR, SKY_COLOR, SKY_COLOR, C_GOLD, C_BROWN, SKY_COLOR, SKY_COLOR, SKY_COLOR
};

const unsigned short _MASK = SKY_COLOR;

const unsigned short M_RED = 0xF801;
const unsigned short M_SKIN = 0xfd28;
const unsigned short M_SHOES = P_BROWN;
const unsigned short M_SHIRT = 0x7BCF;
const unsigned short M_HAIR = BLACK;

//'mario-idle', 13x16px
const uint16_t MARIO_IDLE[] PROGMEM = {
	_MASK, _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, _MASK, _MASK, 
  _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, 
  _MASK, _MASK, M_HAIR, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, _MASK, _MASK, _MASK, 
  _MASK, M_HAIR, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_SKIN, _MASK, 
  _MASK, M_HAIR, M_SKIN, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_SKIN, 
  _MASK, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_HAIR, M_HAIR, M_HAIR, M_HAIR, _MASK, 
  _MASK, _MASK, _MASK, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, _MASK, _MASK, 
  _MASK, _MASK, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, 
  _MASK, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, _MASK, _MASK, 
  M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_RED, M_RED, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, _MASK, 
  M_SKIN, M_SKIN, M_SHIRT, M_RED, M_SKIN, M_RED, M_RED, M_SKIN, M_RED, M_SHIRT, M_SKIN, M_SKIN, _MASK,
  M_SKIN, M_SKIN, M_SKIN, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SKIN, M_SKIN, M_SKIN, _MASK, 
  M_SKIN, M_SKIN, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SKIN, M_SKIN, _MASK, 
  _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, _MASK, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, 
  _MASK, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK, _MASK, _MASK, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK,
  M_SHOES, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK, _MASK, _MASK, M_SHOES, M_SHOES, M_SHOES, M_SHOES, M_SHOES
};


const byte MARIO_IDLE_SIZE[2]  = {13, 16};

const uint16_t MARIO_IDLE_REVERSED [] PROGMEM = {
    _MASK, _MASK, _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, _MASK, 
    _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, 
    _MASK, _MASK, _MASK, _MASK, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_HAIR, M_HAIR, M_HAIR, _MASK, 
    _MASK, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_HAIR, _MASK, 
    M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_HAIR, M_HAIR, M_SKIN, M_HAIR, _MASK, 
    _MASK, M_HAIR, M_HAIR, M_HAIR, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_HAIR, _MASK, 
    _MASK, _MASK, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, _MASK, _MASK, _MASK, 
    _MASK, _MASK, _MASK, _MASK, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, _MASK, 
    _MASK, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_RED, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, 
    M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_RED, M_RED, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, 
    M_SKIN, M_SKIN, M_SKIN, M_SHIRT, M_RED, M_SKIN, M_RED, M_RED, M_SKIN, M_RED, M_SHIRT, M_SKIN, M_SKIN, 
    M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SKIN, M_SKIN, M_SKIN, 
    M_SKIN, M_SKIN, M_SKIN, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SKIN, M_SKIN, M_SKIN, 
    _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, _MASK, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, 
    _MASK, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK, _MASK, _MASK, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK, 
    M_SHOES, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK, _MASK, _MASK, M_SHOES, M_SHOES, M_SHOES, M_SHOES, M_SHOES
};

//'mario-jump', 17x16px
const uint16_t MARIO_JUMP [] PROGMEM = {
	_MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, M_SKIN, M_SKIN, M_SKIN, 
	M_SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, M_SKIN, M_SKIN, 
	M_SKIN, M_SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, 
	M_SKIN, M_SKIN, M_SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, M_HAIR, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, 
	M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, M_HAIR, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, 
	M_SKIN, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, M_HAIR, M_SKIN, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_SKIN, 
	M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, M_HAIR, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_SKIN, 
	M_HAIR, M_HAIR, M_HAIR, M_HAIR, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, M_SKIN, M_SKIN, M_SKIN, 
	M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, 
	M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, 
	M_SHIRT, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_RED, _MASK, M_SHOES, M_SHOES, M_SKIN, M_SKIN, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, 
	M_SHIRT, M_SHIRT, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, M_SHOES, M_SHOES, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_RED, 
	M_RED, M_SHIRT, M_RED, M_RED, M_SKIN, M_RED, M_RED, M_SKIN, M_RED, M_SHOES, M_SHOES, M_SHOES, _MASK, M_SKIN, M_SKIN, M_SHOES, 
	M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SHOES, M_SHOES, M_SHOES, _MASK, _MASK, M_SHOES, 
	M_SHOES, M_SHOES, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SHOES, M_SHOES, M_SHOES, _MASK, M_SHOES, 
	M_SHOES, M_SHOES, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, 
	M_SHOES, M_SHOES, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK
};

const uint16_t MARIO_JUMP_REVERSED [] PROGMEM = {
    M_SKIN, M_SKIN, M_SKIN, M_SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, 
    M_SKIN, M_SKIN, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, 
    M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, _MASK, _MASK, _MASK, M_SKIN, M_SKIN, 
    M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_HAIR, M_HAIR, M_HAIR, _MASK, _MASK, _MASK, _MASK, 
    M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_HAIR, M_SKIN, M_HAIR, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, _MASK, _MASK, 
    M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_SKIN, M_HAIR, M_SKIN, M_SKIN, M_HAIR, M_HAIR, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, 
    M_SHIRT, M_SHIRT, M_SHIRT, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_HAIR, M_HAIR, M_HAIR, M_HAIR, M_HAIR, _MASK, _MASK, _MASK, _MASK, 
    M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, 
    M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, _MASK, _MASK, _MASK, _MASK, 
    M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_RED, M_RED, _MASK, _MASK, 
    M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SHIRT, M_SHIRT, M_SHIRT, M_SHIRT, M_SKIN, M_SKIN, M_SHOES, M_SHOES, _MASK, M_SHOES, 
    M_RED, M_RED, M_RED, M_RED, M_SHIRT, M_RED, M_SHOES, M_SHOES, _MASK, M_RED, M_RED, M_SKIN, M_SKIN, M_SKIN, M_SKIN, M_SHOES, 
    M_RED, M_RED, M_SKIN, M_RED, M_RED, M_RED, M_SKIN, M_SKIN, _MASK, M_SHOES, M_SHOES, M_SHOES, M_RED, M_RED, M_SKIN, _MASK, 
    M_SHOES, M_SHOES, M_SHOES, M_SHOES, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_SHOES, M_SHOES, _MASK, _MASK, 
    M_SHOES, M_SHOES, M_SHOES, M_SHOES, M_SHOES, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, _MASK, 
    _MASK, _MASK, _MASK, _MASK, _MASK, M_RED, M_RED, M_RED, M_RED, M_RED, _MASK, M_SHOES, M_SHOES, _MASK, _MASK, _MASK
};

const byte MARIO_JUMP_SIZE[2]  = {17, 16};


